name: Release

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  update_release_draft:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.base_ref == 'main'
    steps:
      - name: Create Release
        uses: release-drafter/release-drafter@v5.23.0
        if: github.base_ref == 'main'
        with:
          publish: true
          commitish: main
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
